name: Care_AI
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.2
  phone_numbers_parser: ^9.0.0
  image_picker: ^1.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
