// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohmmMIBzCjuVAoteWmLYmh77ZVpqYIxk',
    appId: '1:1037784419913:web:6a18c3db7387c8e206f998',
    messagingSenderId: '1037784419913',
    projectId: 'careai-c7ce0',
    authDomain: 'careai-c7ce0.firebaseapp.com',
    storageBucket: 'careai-c7ce0.firebasestorage.app',
    measurementId: 'G-FCT4KS35M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6-u0gvLTIPpxxKbDQUNueE2VoXqc0Iw',
    appId: '1:1037784419913:android:31aad18bb7fefd5d06f998',
    messagingSenderId: '1037784419913',
    projectId: 'careai-c7ce0',
    storageBucket: 'careai-c7ce0.firebasestorage.app',
  );
}
